### ISSUE TITLE
Document undefined

### ISSUE THREAD

**Issue by mserege** [egoist/style-inject#5]
Hi,

Going from 0.1.2 to 0.2.0 made verification of document variable definition disappeared.

`
if (typeof document === 'undefined') {		
  return returnValue;		
}
`

Would it be possible to put it back so my module can work on server-side without throwing an exception?

Thanks

**Comment by egoist** [comment]
If you're authoring a js library, it should always extract css 😄

but yeah, we can make it `return` when `document` is `undefined`

**Comment by egoist** [comment]
Fixed in `v0.2.1`
